// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use Neon’s direct endpoint for schema migrations when it is available.
    // The application itself continues to use DATABASE_URL (the pooled endpoint).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
