ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REFUNDING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REFUNDED';

UPDATE "Order"
SET "status" = 'PROCESSING'
WHERE "status" = 'UNDER_REVIEW';

ALTER TABLE "Order"
ALTER COLUMN "status" SET DEFAULT 'PENDING_PAYMENT';
